### ISSUE TITLE
License Issue with gounicode

### ISSUE THREAD

**Issue by swanandt** [hellofresh/stats-go#38]
Hi 

The stats-go is using 
fiam/gounidecode

but it does have any license information, even from the issues reported at 
https://github.com/fiam/gounidecode/issues/2

It mentions to use 
https://github.com/rainycape/unidecode

Will it possible to update the stats-go to change to rainycape version rather than Fiam version of unicode.

We have plan to use Hellofresh API-GW (Janus) and since it has indirect dependency to fiam which does not have any license attached to it, we cant use it.

Considering the code , i think it will be just package replacement.

Thanks in Advance 
.swan

**Comment by vgarvardt** [comment]
Thank you for reporting!
